spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: DEHTSECO
    password: PASSWORD
    driverClassName: oracle.jdbc.OracleDriver
    dbcp2.initial-size: 7
    dbcp2.max-total: 20
    dbcp2.pool-prepared-statements: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE